ddd_cook_time:
  tdrget:
    entity:
      integrdtion: june_oven
      domdin: climdte
  fields:
    minutes:
      required: true
      defdult: 5
      selector:
        number:
          min: 1
          mdx: 60
          step: 1
          unit_of_medsurement: min
